package com.komida.co.id.mdisujikelayakan.model

import android.graphics.drawable.Drawable

class ListAgtUKAll(
    var label: String, // Assuming "$nama<br><small>$nik - $nama - $no_center</small>"
    var kode_uk: String?,
    var cabang: String?,
    var tipe: String?,
    var nama: String?,
    var nik: String?,
    var tahun_kadaluarsa: String?,
    var tempat_lahir: String?,
    var tgl_lahir: String?,
    var nama_suami: String?,
    var status_kawin: String?,
    var rt: String?,
    var rw: String?,
    var desa: String?,
    var kecamatan: String?,
    var kabupaten: String?,
    var no_id: String?,
    var no_center: String?,
    var kelompok: String?,
    var tgl_pengambilan_data: String?,
    var tgl_bergabung: String?,
    var nama_ibu_kandung: String?,
    var tempat_tgl_ortu: String?,
    var wilayah: String?,
    var cek_client: String?,
    var handphone: String?,
    var cek_pnjmn_koperasi: String?,
    var cek_pnjmn_bank: String?,
    var cek_tidak_ada_akses: String?,
    var cek_rekening_tabungan: String?,
    var cek_asuransi: String?,
    var cek_anggota_komida: String?,
) {
    // Primary constructor

    // Additional constructor
    constructor(
        kode_uk :String,
        cabang :String,
        tipe :String,
        nama :String,
        nik :String,
        tahun_kadaluarsa :String,
        tempat_lahir :String,
        tgl_lahir :String,
        nama_suami :String,
        status_kawin :String,
        rt :String,
        rw :String,
        desa :String,
        kecamatan :String,
        kabupaten :String,
        no_id :String,
        no_center :String,
        kelompok :String,
        tgl_pengambilan_data :String,
        tgl_bergabung :String,
        nama_ibu_kandung :String,
        tempat_tgl_ortu :String,
        wilayah :String,
        cek_client :String,
        handphone :String,
        cek_pnjmn_koperasi :String,
        cek_pnjmn_bank :String,
        cek_tidak_ada_akses :String,
        cek_rekening_tabungan :String,
        cek_asuransi :String,
        cek_anggota_komida :String
    ) : this(
        "$nama<br><small>$nik - $nama - $no_center</small>",
        kode_uk,
        cabang,
        tipe,
        nama,
        nik,
        tahun_kadaluarsa,
        tempat_lahir,
        tgl_lahir,
        nama_suami,
        status_kawin,
        rt,
        rw,
        desa,
        kecamatan,
        kabupaten,
        no_id,
        no_center,
        kelompok,
        tgl_pengambilan_data,
        tgl_bergabung,
        nama_ibu_kandung,
        tempat_tgl_ortu,
        wilayah,
        cek_client,
        handphone,
        cek_pnjmn_koperasi,
        cek_pnjmn_bank,
        cek_tidak_ada_akses,
        cek_rekening_tabungan,
        cek_asuransi,
        cek_anggota_komida
    )
}