package com.komida.co.id.mdisujikelayakan.model
class ModelListKelompok(
    var label: String? = null,
    var kode_uk_trx_lwk: String? = null,
    var no_trx_lwk: String? = null,
    var tgl_input: String? = null,
    var cabang: String? = null,
    var no_center: String? = null,
    var nama_center: String? = null,
    var no_kelompok: String? = null,
    var nama_kelompok: String? = null,
    var tempat: String? = null,
    var waktu: String? = null,
    var ketua_center:String?= null,
    var wakil_ketua_center:String?= null,
    var ketua_kelompok:String?= null,
    var wakil_ketua_kelompok:String?= null,
    var petugas:String?= null,
    var ttd_petugas:String?= null,
    var kategori_lwk:String?= null,
    var penerima_kedua:String?= null,
    var section: Boolean = false,
    var isExpanded: Boolean = false,
    var isHeader: Boolean = false
) {
    constructor(
        label: String,
        kode_uk_trx_lwk:String,
        no_trx_lwk:String,
        tgl_input:String,
        cabang:String,
        no_center:String,
        nama_center:String,
        no_kelompok:String,
        nama_kelompok:String,
        tempat:String,
        waktu:String,
        ketua_center:String,
        wakil_ketua_center:String,
        ketua_kelompok: String,
        wakil_ketua_kelompok: String,
        petugas: String,
        ttd_petugas: String,
        kategori_lwk: String,
        penerima_kedua: String,
        isHeader: Int,
        isExpanded: Boolean,
        section: Boolean,
        additionalParameter: Int
    ) : this(
        "$no_trx_lwk<br>",
        kode_uk_trx_lwk,
        no_trx_lwk,
        tgl_input,
        cabang,
        no_center,
        nama_center,
        no_kelompok,
        nama_kelompok,
        tempat,
        waktu,
        ketua_center,
        wakil_ketua_center,
        ketua_kelompok,
        wakil_ketua_kelompok,
        petugas,
        ttd_petugas,
        kategori_lwk,
        penerima_kedua,
        isHeader != 0,
        isExpanded,
        section
    )
}
